apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- cert.yaml
- config-map.yaml
- cluster-role-binding.yaml
- cluster-role.yaml
- secret.yaml
- statefulset.yaml
- service.yaml
- webhook.yaml
commonLabels:
  kustomize.component: kfserving
generatorOptions:
 disableNameSuffixHash: true
configMapGenerator:
- envs:
  - params.env
  name: kfserving-config
vars:
- name: registry
  objref:
    kind: ConfigMap
    name: kfserving-config
    apiVersion: v1
  fieldref:
    fieldpath: data.registry
configurations:
- params.yaml
images:
- name: kubebuilder/kube-rbac-proxy
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: kube-rbac-proxy-1.0.2
- name: kfserving/kfserving-controller
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: kfserving-controller-v0.3.0
