# Define a transform to remove namespace from cluster scoped resources
apiVersion: v1alpha1 
kind: RemoveNamespace
metadata:
  name: remove-namespace
  annotations:
    config.kubernetes.io/function: |
      container:
        image: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new:kpt-fns-v1.1
spec:
  clusterKinds:
  - kind: Profile
    group: kubeflow.org
  - kind: ClusterIssuer
    group: cert-manager.io
  - kind: CompositeController
    group: metacontroller.k8s.io
  - kind: ClusterRbacConfig
    group: rbac.istio.io
 