apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: knative-serving
resources:
- ../../knative-serving-crds/base
- ../../knative-serving-crds/overlays/application
- ../../knative-serving-install/base/gateway.yaml
- ../../knative-serving-install/base/cluster-role.yaml
- ../../knative-serving-install/base/cluster-role-binding.yaml
- ../../knative-serving-install/base/service-role.yaml
- ../../knative-serving-install/base/service-role-binding.yaml
- ../../knative-serving-install/base/config-map.yaml
- ../../knative-serving-install/base/deployment.yaml
- ../../knative-serving-install/base/secret.yaml
- ../../knative-serving-install/base/service-account.yaml
- ../../knative-serving-install/base/service.yaml
- ../../knative-serving-install/base/image.yaml
- ../../knative-serving-install/base/hpa.yaml
- ../../knative-serving-install/base/webhook-configuration.yaml
- ../../knative-serving-install/overlays/application
commonLabels:
  kustomize.component: knative
  app.kubernetes.io/component: knative-serving-install
  app.kubernetes.io/name: knative-serving-install
images:
- name: knative-releases/knative.dev/serving/cmd/activator
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: serving-activator-v0.14.3
- name: knative-releases/knative.dev/serving/cmd/autoscaler
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: serving-autoscaler-v0.14.3
- name: knative-releases/knative.dev/serving/cmd/webhook
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: serving-webhook-v0.14.3
- name: knative-releases/knative.dev/serving/cmd/controller
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new:serving-controller-v0.14.3
  newTag: serving-controller-v0.14.3
- name: knative-releases/knative.dev/net-istio/cmd/controller
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: net-istio-controller-v0.14.1
- name: knative-releases/knative.dev/net-istio/cmd/webhook
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: net-istio-webhook-v0.14.1

