apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: knative-eventing
resources:
- ../../knative-eventing-crds/base
- ../../knative-eventing-crds/overlays/application
- ../../knative-eventing-install/base/cluster-role.yaml
- ../../knative-eventing-install/base/cluster-role-binding.yaml
- ../../knative-eventing-install/base/secret.yaml
- ../../knative-eventing-install/base/config-map.yaml
- ../../knative-eventing-install/base/deployment.yaml
- ../../knative-eventing-install/base/service-account.yaml
- ../../knative-eventing-install/base/service.yaml
- ../../knative-eventing-install/base/webhook-configuration.yaml
- ../../knative-eventing-install/overlays/application
commonLabels:
  kustomize.component: knative
  app.kubernetes.io/component: knative-eventing-install
  app.kubernetes.io/name: knative-eventing-install
images:
- name: knative-releases/knative.dev/eventing/cmd/controller
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: eventing-controller-v0.14.2
- name: knative-releases/knative.dev/eventing/cmd/channel_broker
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: eventing-channel_broker-v0.14.2
- name: knative-releases/knative.dev/eventing/cmd/webhook
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: eventing-webhook-v0.14.2
- name: knative-releases/knative.dev/eventing/cmd/in_memory/channel_controller
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: eventing-channel_controller-v0.14.2
- name: knative-releases/knative.dev/eventing/cmd/in_memory/channel_dispatcher
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: eventing-channel_dispatcher-v0.14.2
