---
apiVersion: caching.internal.knative.dev/v1alpha1
kind: Image
metadata:
  labels:
    serving.knative.dev/release: v0.14.3
  name: queue-proxy
  namespace: knative-serving
spec:
  image: 'registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new:serving-queue-v0.14.3'
