apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: knative-serving
resources:
- gateway.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
- service-role.yaml
- service-role-binding.yaml
- config-map.yaml
- deployment.yaml
- secret.yaml
- service-account.yaml
- service.yaml
- image.yaml
- hpa.yaml
- webhook-configuration.yaml
commonLabels:
  kustomize.component: knative
images:
- name: knative-releases/knative.dev/serving/cmd/activator
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: serving-activator-v0.14.3
- name: knative-releases/knative.dev/serving/cmd/autoscaler
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: serving-autoscaler-v0.14.3
- name: knative-releases/knative.dev/serving/cmd/webhook
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: serving-webhook-v0.14.3
- name: knative-releases/knative.dev/serving/cmd/controller
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: serving-controller-v0.14.3
- name: knative-releases/knative.dev/net-istio/cmd/controller
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: net-istio-controller-v0.14.1
- name: knative-releases/knative.dev/net-istio/cmd/webhook
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: net-istio-webhook-v0.14.1
