apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spartakus
  name: spartakus-volunteer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spartakus-volunteer
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - args:
        - volunteer
        - --cluster-id=$(USAGE_ID)
        - --database=https://stats-collector.kubeflow.org
        image: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new:spartakus-amd64-1.0.2
        name: volunteer
        env:
        - name: USAGE_ID
          valueFrom:
            configMapKeyRef:
              name: spartakus-config
              key: usageId
      serviceAccountName: spartakus
