apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- service-account.yaml
commonLabels:
  kustomize.component: spartakus
images:
- name: google_containers/spartakus-amd64
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: spartakus-amd64-1.0.2
configMapGenerator:
- name: spartakus-config
  envs:
  - params.env
generatorOptions:
  disableNameSuffixHash: true
configurations:
- params.yaml
