apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- job.yaml
- certificate.yaml
namespace: kubeflow
commonLabels:
  kustomize.component: iap-ingress
images:
- name: kubeflow-images-public/ingress-setup
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: ingress-setup-latest
