# TODO(https://github.com/kubeflow/manifests/issues/1052) clean
# up this kustomization.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend-config.yaml
- cloud-endpoint.yaml
- cluster-role-binding.yaml
- cluster-role.yaml
- config-map.yaml
- deployment.yaml
- ingress.yaml
- policy.yaml
- service-account.yaml
- service.yaml
- stateful-set.yaml
namespace: kubeflow
commonLabels:
  kustomize.component: iap-ingress
images:
- name: kubeflow-images-public/envoy
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: envoy-1.0.2
- name: kubeflow-images-public/ingress-setup
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: ingress-setup-latest
- name: cloud-solutions-group/esp-sample-app
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: esp-sample-app-1.0.0
configMapGenerator:
- name: parameters
  envs:
  - params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: namespace
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.namespace
- name: appName
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.appName
- name: hostname
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.hostname
- name: ipName
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.ipName
- name: ingressName
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.ingressName
- name: oauthSecretName
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.oauthSecretName
- name: project
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.project
- name: adminSaSecretName
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.adminSaSecretName
- name: tlsSecretName
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.tlsSecretName
- name: istioNamespace
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.istioNamespace
configurations:
- params.yaml
