apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- ../../upstream/kfserving.yaml
- cluster-role.yaml
- application.yaml
commonLabels:
  app: kfserving
  kustomize.component: kfserving
  app.kubernetes.io/component: kfserving
  app.kubernetes.io/name: kfserving
generatorOptions:
 disableNameSuffixHash: true
patchesStrategicMerge:
- configmap-patch.yaml
- statefulset-patch.yaml
images:
- name: kubebuilder/kube-rbac-proxy
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: kube-rbac-proxy-1.0.2
- name: kfserving/kfserving-controller
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: kfserving-controller-v0.4.1
