apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-auth-login
spec:
  selector:
    matchLabels:
      app: basic-auth-login
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: basic-auth-login
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: app
        image: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new:kflogin-ui-v0.5.0:v0.5.0
        ports:
        - containerPort: 5000
