apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kflogin-deployment.yaml
- gatekeeper-deployment.yaml
- gatekeeper-service.yaml
- kflogin-service.yaml
commonLabels:
  kustomize.component: basic-auth
namespace: kubeflow
images:
- name: kubeflow-images-public/kflogin-ui
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: kflogin-ui-v0.5.0
- name: kubeflow-images-public/gatekeeper
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new:gatekeeper-v0.5.0
  newTag: gatekeeper-v0.5.0
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: basic-auth-parameters
  envs:
  - params.env
vars:
- name: service-namespace
  objref:
    kind: Service
    name: basic-auth-login
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace
- name: authSecretName
  objref:
    kind: ConfigMap
    name: basic-auth-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.authSecretName
- name: clusterDomain
  objref:
    kind: ConfigMap
    name: basic-auth-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.clusterDomain
configurations:
- params.yaml
