apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: istio-install-config
  envs:
  - ../base/params.env
images:
- name: docker.io/prom/prometheus
  newTag: v2.8.0
- name: istio-release/citadel
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: citadel-release-1.3-latest-daily
- name: istio-release/galley
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: galley-release-1.3-latest-daily
- name: istio-release/kubectl
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: kubectl-release-1.3-latest-daily
- name: istio-release/mixer
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: mixer-release-1.3-latest-daily
- name: istio-release/node-agent-k8s
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: node-agent-k8s-release-1.3-latest-daily
- name: istio-release/pilot
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: pilot-release-1.3-latest-daily
- name: istio-release/proxyv2
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: proxyv2-release-1.3-latest-daily
- name: istio-release/sidecar_injector
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: sidecar_injector-release-1.3-latest-daily
resources:
- ../base/namespace.yaml
- ../base/attribute-manifest.yaml
- ../base/config-map.yaml
- ../base/cluster-role.yaml
- ../base/cluster-role-binding.yaml
- ../base/daemon-set.yaml
- ../base/deployment.yaml
- ../base/handler.yaml
- ../base/horizontal-pod-autoscaler.yaml
- ../base/instance.yaml
- ../base/job.yaml
- ../base/mutating-webhook-configuration.yaml
- ../base/pod-disruption-budget.yaml
- ../base/role.yaml
- ../base/role-binding.yaml
- ../base/rule.yaml
- ../base/service.yaml
- ../base/service-account.yaml
- ../base/service-role.yaml
- ../base/service-role-binding.yaml
vars:
- name: namespace
  objref:
    kind: ConfigMap
    name: istio-install-config
    apiVersion: v1
  fieldref:
    fieldpath: data.namespace
configurations:
- ../base/params.yaml
