# Each entry in this list results in the creation of
# one ConfigMap resource (it's a generator of n maps).
configMapGenerator:
- name: istio-install-parameters
  envs:
  - params.env

# Images modify the tags for images without
# creating patches.
images:
- name: docker.io/prom/prometheus
  newTag: v2.8.0
- name: istio-release/citadel
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: citadel-release-1.3-latest-daily
- name: istio-release/galley
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: galley-release-1.3-latest-daily
- name: istio-release/kubectl
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: kubectl-release-1.3-latest-daily
- name: istio-release/mixer
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: mixer-release-1.3-latest-daily
- name: istio-release/node-agent-k8s
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: node-agent-k8s-release-1.3-latest-daily
- name: istio-release/pilot
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: pilot-release-1.3-latest-daily
- name: istio-release/proxyv2
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: proxyv2-release-1.3-latest-daily
- name: istio-release/sidecar_injector
  newName: registry.cn-hangzhou.aliyuncs.com/frank_1991/kubeflow_new
  newTag: sidecar_injector-release-1.3-latest-daily

resources:
- namespace.yaml
- attribute-manifest.yaml
- config-map.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
- daemon-set.yaml
- deployment.yaml
- handler.yaml
- horizontal-pod-autoscaler.yaml
- instance.yaml
- job.yaml
- mutating-webhook-configuration.yaml
- pod-disruption-budget.yaml
- role.yaml
- role-binding.yaml
- rule.yaml
- service.yaml
- service-account.yaml
- service-role.yaml
- service-role-binding.yaml

vars:
- name: namespace
  objref:
    kind: ConfigMap
    name: istio-install-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.namespace

configurations:
- params.yaml
